# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

function cpick
{
	local cpick_commit="cpick_commit.tmp"
	local cpick_tmp="cpick_tmp.tmp"
	local cpick_is_error="cpick_is_error.tmp"
    
	OPTIND=0
	while getopts :h opt
	do
		case $opt in
			h)  echo "Usage: cpick [-h] [branchA branchB]"
				return
				;;
			?)	echo "Invalid option, use -h to see usage"
				return
				;;
		esac
	done
	shift $((OPTIND - 1))

	echo 0 > $cpick_is_error
# three argvs, two possible
# 1. new pick -> execute flow
# 2. old pick not complete -> do nothing
	if [ $# -eq 2 ];then
		if [ ! -e $cpick_commit ];then
			git cherry -v $1 $2 > $cpick_commit
			if [ $? -ne 0 ];then
				rm cpick*.tmp
				return
			fi
			sed -i "/^- /d" $cpick_commit
			cut -d " " -f 2 $cpick_commit > $cpick_tmp
			mv $cpick_tmp $cpick_commit
		fi
	fi
# 1. new pick, but commit is null
# 2. old pick, but commit left is null
# 3. error input
	if [ ! -e $cpick_commit ];then
		rm $cpick_is_error
		echo "no commit file"
		echo "usage: cpick [branchA branchB]"
		return
	else
		if [ ! -s $cpick_commit ];then
			echo "commits file is empty, nothing to pick, cherry-pick complete"
			rm cpick*.tmp
			return
		fi
	fi
# cherry-pick commits
	cat $cpick_commit | while read line
	do
		sed -i "/$line/d" $cpick_commit
		git cherry-pick $line
		if [ $? -ne 0 ];then
			echo 1 > $cpick_is_error
			break
		fi
	done

	if [ `cat $cpick_is_error` -eq 1 ];then
		echo -e "\033[31mcherry-pick error, please fix it\033[0m"
		rm $cpick_is_error
		return
	else
		echo -e "\033[32mcherry-pick complete\033[0m"
		rm cpick*.tmp
		return
	fi
}
complete -F __ding_cmd_HUB 2ding
complete -F __ding_cmd_HUB ding
function __ding_cmd
{
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local options="`cut -d " " -f 1 ~/.ding`"
    COMPREPLY=( $(compgen -W "${options}" -- ${cur}) )
}
function __ding_cmd_HUB
{
	case $COMP_CWORD in
	0)  ;;
	1)  if [ ${COMP_WORDS[0]} == 2ding ];then
		    eval __ding_cmd
		fi
		;;
	2)  if [ ${COMP_WORDS[0]} == ding -a ${COMP_WORDS[1]} == '-d' ];then
	        eval __ding_cmd
	    fi
	    ;;
	esac
}
function ding
{
	local DING_FILE_PATH="$HOME/.ding"
	if [ $# -eq 0 ]
	then
		if [ -e $DING_FILE_PATH ]
		then
		    cat $DING_FILE_PATH | sort | while read line
		    do
		        echo -e "\033[31m`echo -n $line | cut -d ' ' -f 1`	\033[36m`echo -n $line | cut -d ' ' -f 2-`\033[0m"
		    done
		else
		    echo "No ding file"
		fi
	fi

	OPTIND=0
	while getopts :Dd:hvz opt
	do
		case $opt in
		d)	if [ -e $DING_FILE_PATH ]
       	    then
       	        grep "^$OPTARG " $DING_FILE_PATH > /dev/null
				ret=$?
				if [ $ret -eq 0 ]
				then
					cp $DING_FILE_PATH "$DING_FILE_PATH.bak"
				fi
				sed -i "/^$OPTARG /d" $DING_FILE_PATH
				if [ $ret -eq 0 ]
				then
					echo -e "\033[31mDel ding \033[36m$OPTARG\033[0m"
				else
					echo -e "\033[31mNo such ding \033[36m$OPTARG\033[0m"
				fi
       	    else
       	        echo "No ding file"
       	    fi
			;;
		D)	if [ -e $DING_FILE_PATH ]
			then
				cp $DING_FILE_PATH "$DING_FILE_PATH.bak"
				rm $DING_FILE_PATH
				echo "Del all dings"
			else
				echo "No ding file"
			fi
			;;
		h)	echo "Usage: ding [-dDzvh] [DING_NAME]"
			echo "ding DING_NAME : store current path to \"DING_NAME\""
			echo "ding : list all stored dings"
			echo "ding -d DING_NAME : delete existing ding named \"DING_NAME\", can user regexp"
			echo "ding -D : delete all dings stored"
			echo "ding -z : roll back the previous revision"
			echo "ding -v : show version"
			echo "ding -h : show usage"
			;;
		v)	echo "Version 3.0"
			echo "Designed by liuqi@microtrust.com.cn"
			;;
		z)	if [ -e "$DING_FILE_PATH.bak" ]
			then
				mv "$DING_FILE_PATH.bak" $DING_FILE_PATH
				echo "Back in time"
			else
				echo "No ding back file"
			fi
			;;
		?)	echo "Invalid option, use -h to see usage"
			;;
		esac
	done

	shift $((OPTIND - 1))
	
	if [ $# -eq 1 ]
    then
        if [ -e $DING_FILE_PATH ]
        then
			cp $DING_FILE_PATH "$DING_FILE_PATH.bak"
            sed -i "/^$1 /d" $DING_FILE_PATH
        fi

        DING_NAME="$1 $PWD"
        echo -e "$DING_NAME" >> $DING_FILE_PATH
        echo -e "\033[31mDing \033[36m$PWD \033[31mto \033[36m$1\033[0m"
	fi
}
function 2ding
{
	local DING_FILE_PATH="$HOME/.ding"
    OPTIND=0
	while getopts :vh opt
	do
		case $opt in
			h)  echo "Usage: 2ding [-vh] [DING_NAME]"
				echo "2ding DING_NAME : jump to the path stored in \"DING_NAME\""
				echo "2ding -v : show version"
				echo "2ding -h : show usage"
				;;
			v)	echo "Version 3.0"
				echo "Designed by liuqi@microtrust.com.cn"
				;;
			?)	echo "Invalid option, use -h to see usage"
				;;
		esac
	done
	shift $((OPTIND - 1))

	path=""
    if [ $# -eq 1 ]
    then
        if [ -e $DING_FILE_PATH ]
        then
            path=`sed -n "/^$1 /p" $DING_FILE_PATH`
            if [ "$path" != "" ]
            then
                cd "`echo -n "$path" | cut -d ' ' -f 2-`"
            else
                echo "Not find path"
            fi
        else
            echo "No ding file"
        fi
    fi
}

complete -c vcmd
function vcmd
{
    local result=`which $1`
    if [ -n "$result" ];then
        vim `echo $result | cut -d ' ' -f 3`
    else
        type $1
    fi
}
complete -c ccolor
function ccolor
{
    local arr1=(warning#YELLOW#error#RED#failed#RED#fail#RED#note#BLUE#\
                警告#YELLOW#错误#RED#附注#BLUE#\
				undefined reference#RED)
    local except=("make setup" "")
    local RED="\033[0;31m"
    local RED1="\033[1;031m"
    local YELLOW="\033[0;33m"
    local YELLOW1="\033[1;33m"
    local BLUE="\033[0;34m"
    local BLUE1="\033[1;34m"
    local END="\033[0m"

    shopt -u expand_aliases

	for ((i=0;i<${#except[@]};i++))
    do
        if [ z"${except[$i]}" == z"$*" ]
        then
            eval "$*"
            shopt -s expand_aliases
            return
        fi
    done

    eval "$*" 2>&1 | awk -v arr2="${arr1[*]}" '
    BEGIN{n=split(arr2,arr3,"#");normal_print=1}
    {
        IGNORECASE=1;
        for(i=1;i<=n;i=i+2){
             if((match($0,"[ \t:]+"arr3[i]"[s]*[ \t:]+"))||
                (match($0,"^"arr3[i]"[s]*[ \t:]+"))||
                (match($0,"[ \t:]+"arr3[i]"[s]*$"))||
                (match($0,"^"arr3[i]"[s]*$"))){
                 len_s=RLENGTH;
                 pos=RSTART;
                 len=length($0);
                 pos1=pos+len_s;
                 b=substr($0, 1, pos-1);
                 m=substr($0, pos, RLENGTH);
                 a=substr($0, pos1, len-pos1+1);
                 switch(arr3[i+1]){
                     case /YELLOW/:
                         print "'"$YELLOW"'"b"'"$YELLOW1"'"m"'"$YELLOW"'"a"'"$END"'";
                         break;
                     case /RED/:
                         print "'"$RED"'"b"'"$RED1"'"m"'"$RED"'"a"'"$END"'";
                         break;
                     case /BLUE/:
                         print "'"$BLUE"'"b"'"$BLUE1"'"m"'"$BLUE"'"a"'"$END"'";
                         break;
                     default:
                         print "Color setting wrong! Please check ~/.bashrc ccolor func"
                 }
                 normal_print=0;
                 break;
             }
        }
        if(normal_print)
            print;
        else
            normal_print=1;
    }'
    shopt -s expand_aliases
}

alias gcc="ccolor gcc"
alias g++="ccolor g++"
alias make="ccolor make"
alias mm="ccolor mm"
alias mmm="ccolor mmm"
alias zhmakepkg="ccolor zhmakepkg"
alias soter_make="ccolor soter_make"
alias sboot_make="ccolor sboot_make"

function get_repo_root
{
    repo info > /dev/null 2>&1
    if [ $? != 0 ]; then
        return
    fi

    export REPO_ROOT_PATH=`repo info | grep "Mount path" | head -1 | grep -o '/.*/'`
}
complete -F __rmake_cmd_HUB rmake
function __rmake_cmd
{
    get_repo_root
    if [ -z "$REPO_ROOT_PATH" ]; then
        return
    fi

    local cur="${COMP_WORDS[COMP_CWORD]}"
    local options="`cd $REPO_ROOT_PATH && make -pRrq : 2>/dev/null | awk -v RS= -F: '/^# File/,/^# Finished Make data base/ {if ($1 !~ "^[#.]") {print $1}}' | egrep -v '^[^[:alnum:]]' | sort`"
    COMPREPLY=( $(compgen -W "${options}" -- ${cur}) )
}
function __rmake_cmd_HUB
{
    case $COMP_CWORD in
    0)  ;;
    1)  if [ ${COMP_WORDS[0]} == rmake ];then
            eval __rmake_cmd
        fi
        ;;
    esac
}
function rmake
{
    OST_CURRENT_FOLDER=`pwd`
    get_repo_root
    if [ -z "$REPO_ROOT_PATH" ]; then
        return
    fi

    OPTIND=0
    while getopts :h opt
    do
        case $opt in
            h)
                echo "Usage: rmake [-h] [REPO_MAKE_COMMAND]"
                echo "       @REPO_MAKE_COMMAND: same as normal make command in repo"
                echo "       @-h : show usage"
                echo "       You don't need to switch folder for compile now"
                echo "       You can use this command in repo root folder or sub folders directly"
                echo "       And rmake can auto completion"
                return
                ;;
            ?)
                echo "Invalid option, use -h to see usage"
                return
                ;;
        esac
    done
    shift $((OPTIND - 1))

    (cd $REPO_ROOT_PATH && eval make $* OST_CURRENT_FOLDER=$OST_CURRENT_FOLDER)
}
complete -F __rgo_cmd_HUB rgo
function __rgo_cmd
{
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local options="ost build prj project soter mdl pkg ws workshop android release rls"
    COMPREPLY=( $(compgen -W "${options}" -- ${cur}) )
}
function __rgo_cmd_HUB
{
    case $COMP_CWORD in
    0)  ;;
    1)  if [ ${COMP_WORDS[0]} == rgo ]; then
            eval __rgo_cmd
        fi
        ;;
    esac
}
function rgo
{
    get_repo_root
    if [ -z "$REPO_ROOT_PATH" ]; then
        return
    fi

    if [ $# -gt 0 ]; then
        while [ -n "$1" ]; do
            case $1 in
                ost)
                    cd $REPO_ROOT_PATH
            break
                ;;
                build)
                    cd $REPO_ROOT_PATH/build
            break
                ;;
                prj|project)
                    cd $REPO_ROOT_PATH/build/projects
            break
                ;;
                release|rls)
                    PROJECT_NAME=`rmake show_env | grep DEV_CUR_PROJECT | awk -F '=' '{print $2}' | sed 's/\s//g'`
            cd $REPO_ROOT_PATH/obj/$PROJECT_NAME/release
            break
                ;;
                mdl)
                    SOTER_PLATFORM_NAME=`rmake info | grep DEV_TARGET_PLATFORM | awk -F '=' '{print $2}' | sed 's/\s//g'`
                    cd $REPO_ROOT_PATH/soter/src/l4/conf/modulelist_${SOTER_PLATFORM_NAME}
            break
                ;;
                pkg)
                    cd $REPO_ROOT_PATH/soter/src/l4/pkg
            break
                ;;
                soter)
                    cd $REPO_ROOT_PATH/soter
            break
                ;;
                ws|workshop)
                    cd $REPO_ROOT_PATH/workshop
            break
                ;;
                android)
                    cd $REPO_ROOT_PATH/android
            break
                ;;
                *)
                    echo "Unkown place name."
            break
                ;;
            esac
        done
    else
        cd $REPO_ROOT_PATH
    fi
}
alias up='cd ..'

function fwq
{
    local local_cmd=(
        "git push"
        "repo upload"
    )
    cmd="$*"
    current_dir=`pwd`
    mount_detail=`cat /proc/mounts | grep cooli7wa@192.168.8.66`
    if [ $? != 0 ];then
        echo "No mount"
        return 1
    fi
    mount_num=`echo "$mount_detail" | wc -l`
    if [ $mount_num -gt 1 ];then
        echo "You have more than one mount dirs, please umount one and try again"
        cat /proc/mounts | grep cooli7wa@192.168.8.66
        return 1
    fi
    mount_dir=`cat /proc/mounts | grep cooli7wa@192.168.8.66 | cut  -d ' ' -f 2`
    remote_dir=`cat /proc/mounts | grep cooli7wa@192.168.8.66 | cut  -d ' ' -f 1 | cut -d ':' -f 2`
    echo $current_dir | grep -q $mount_dir
    if [ $? != 0 ]; then
        echo "Not in mount dir"
        return 1
    fi
    for lcmd in "${local_cmd[@]}"
    do
        echo "$*" | grep -q "^$lcmd"
        if [ $? == 0 ]; then
            eval $*
            return 0
        fi
    done
    relate_dir=${current_dir#$mount_dir}
    echo "cd $remote_dir/$relate_dir; $cmd"
    ssh -t cooli7wa@192.168.8.66 "cd $remote_dir/$relate_dir; eval $cmd"
    return 0
}
function _fwq_rm_folder
{
    local folder=$1

    ssh cooli7wa@192.168.8.66 " \
    cd /home/1t/aufs/user_data; \
    if [ -e ./$1 ]; then \
        echo "rm $1"; \
        rm -rf ./$1 || exit 1; \
    fi" || return 1
    return 0
}
function _fwq_umount_rm_folder
{
    local folder=$1

    ssh cooli7wa@192.168.8.66 " \
    cd /home/1t/aufs/user_data; \
    cat /proc/mounts | grep -q "/user_data/$folder"; \
    if [ \$? == 0 ]; then \
        echo "umount $folder"; \
        sudo umount ./$folder || exit 1; \
        echo "rm $folder"; \
        rm -rf ./$folder || exit 1; \
    elif [ -d $folder ]; then \
        echo "rm $folder"; \
        rm -rf ./$folder || exit 1; \
    fi" || return 1
    return 0
}
function _fwq_create_folder
{
    local folder=$1

    ssh cooli7wa@192.168.8.66 " \
    cd /home/1t/aufs/user_data; \
    echo "mkdir $1"; \
    mkdir $1 || exit 1" || return 1
    return 0
}
function _fwq_mount_folder
{
    local user_name=$1

    ssh cooli7wa@192.168.8.66 " \
    cd /home/1t/aufs/user_data; \
    echo "mount mnt_$user_name"; \
    sudo mount -t overlay overlay -o upperdir=./.container_$user_name,lowerdir=/home/1t/aufs/ost,workdir=./.work_$user_name ./mnt_$user_name || exit 1" || return 1
    return 0
#sudo mount -t aufs -o dirs=./.container_$user_name:/home/1t/aufs/ost none ./mnt_$user_name || exit 1" || return 1
}
function _fwq_clean_folder
{
    local user_name=$1

    _fwq_rm_folder ".container_$user_name" || return 1
    _fwq_rm_folder ".work_$user_name" || return 1
    _fwq_umount_rm_folder "mnt_$user_name" || return 1
    return 0
}
function _fwq_make_folder
{
    local user_name=$1

    _fwq_create_folder ".container_$user_name" || return 1
    _fwq_create_folder ".work_$user_name" || return 1
    _fwq_create_folder "mnt_$user_name" || return 1
    _fwq_mount_folder "$user_name" || return 1
    _fwq_post_flow "$user_name" || return 1
    return 0
}
function _fwq_post_flow
{
    local user_name=$1
    return 0
}
function fwq_mount
{
    if [ -z "$1" ]; then
        echo "Please enter mnt_dir, such as: fwq_mount ./mnt"
        return 1
    fi
    if [ ! -d "$1" ]; then
        echo "Dir $1 not exist"
        return 1
    fi
	local fwq_status=`ssh cooli7wa@192.168.8.66 "cat /home/1t/aufs/log/mount.lock"`
	if [ -n "$fwq_status" ]; then
		echo "fwq not ready, please wait for a moment"
		echo "current status: $fwq_status"
		return 1
	fi
    local local_mount_dir=$1
    local user_name=$USER
    local fwq_user_folder_num=`ssh cooli7wa@192.168.8.66 "ls -a -1 /home/1t/aufs/user_data | grep $user_name | wc -l"`
    local fwq_already_mount=`ssh cooli7wa@192.168.8.66 "cat /proc/mounts | grep -q "/user_data/mnt_$user_name"" && echo yes`
    local choose=0

    if [[ "z$fwq_user_folder_num" == "z3" && "z$fwq_already_mount" == "zyes" ]]; then
        echo "fwq already has this user's folder, please choose:"
        echo "1, mount this folder to $local_mount_dir"
        echo "2, clean and create a new folder, then mount"
        read choose
    fi

    if [ $choose != 1 ]; then
        _fwq_clean_folder "$user_name" || return 1
        _fwq_make_folder "$user_name" || return 1
    fi
    cat /proc/mounts | grep -q "cooli7wa@192.168.8.66.*`realpath $1`.*fuse.sshfs"
    if [ $? == 0 ]; then
        echo "umount local dir $local_mount_dir"
        fusermount -u $1 || return 1
    fi
    echo "mount local dir $local_mount_dir"
    sshfs cooli7wa@192.168.8.66:/home/1t/aufs/user_data/mnt_$user_name $local_mount_dir || return 1
    return 0
}

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export PATH=$PATH:/usr/local/go/bin
export GOPATH=~/go
export GOBIN=$GOPATH/bin
export GOROOT=/usr/local/go
