#!/bin/bash -

#make sure manifest point to a exist xml
repo init -m all_trunk.xml

REPO_ROOT=`repo info | grep "Mount path" | head -1 | grep -o '/.*/'`
CUSTOM_FOLDER=$REPO_ROOT/customization/
TMP_FOLDER=$CUSTOM_FOLDER/tmp
TARGET_FOLDER=$TMP_FOLDER
PHONE_NAME_FILE=$TARGET_FOLDER/phone_name
XML_FILE=$TARGET_FOLDER/phone_setting.xml
PHONE_NAME=""
PHONE_STABLE_BRANCH=`grep -oP '<default revision="\Kstable_[\d.]+' $CUSTOM_FOLDER/common/phone_setting.xml`

#TODO: should check if null, and affirm
#TODO: should check name is unique
read -p "Please input phone name: " PHONE_NAME
if [ -z $PHONE_NAME ];then
echo -e "\033[31mphone name is null\033[0m"
exit 1
fi

if [ -d $TARGET_FOLDER ];then
	rm -rf $TARGET_FOLDER
fi
mkdir $TARGET_FOLDER

cp $CUSTOM_FOLDER/common/phone_setting.xml $XML_FILE
echo $PHONE_NAME > $PHONE_NAME_FILE

echo -e "\033[33mBegin to repo init and sync..\033[0m"
repo init -m ../../customization/tmp/phone_setting.xml
repo sync -d > /dev/null
#repo forall -i ost/build -c git reset --hard ut_repo/$PHONE_STABLE_BRANCH
#repo forall -i ost/build -c git clean -df
echo -e "\033[33mCheckout to tmp phone branch for develop..\033[0m"
#TODO: should check first
repo abandon $PHONE_NAME
repo forall -i ost/build -c git checkout -b $PHONE_NAME
#TODO: should add stable key patches for phone
echo ""
echo -e "\033[32mStart \"$PHONE_NAME\" success\033[0m"
echo "(use \"stash\" to save develop status, \"finish\" to complete develop)"
