#!/bin/bash -

REPO_ROOT=`repo info | grep "Mount path" | head -1 | grep -o '/.*/'`
ALL_PROJECT_FOLDER=`repo list | cut -d ' ' -f 1`
COMMON_FOLDER_PATH=$REPO_ROOT/customization/common
PHONE_HELPER_FOLDER_PATH=$REPO_ROOT/tools_manager/phone_helper
STABLE_VERSION=""

source $PHONE_HELPER_FOLDER_PATH/_phone_utils

#list current stable version
CURRENT_STABLE_LIST=`cd $COMMON_FOLDER_PATH; ls -1`
echo_color YELLOW "Please choose stable version: "
choose_one "$CURRENT_STABLE_LIST" STABLE_VERSION

STABLE_FOLDER_PATH=$REPO_ROOT/customization/common/$STABLE_VERSION
TARGET_FOLDER_PATH=$STABLE_FOLDER_PATH

####################################################################################

#check uncommit changes
check_uncommit_changes
if [ $? != 0 ];then
	echo_color YELLOW "You have uncommit changes, \"finish\" will not record these changes"
	echo_color YELLOW "Are you sure to continue?(y/N)"
	read choose
	if [[ ! "z$choose" =~ ^z[yY](es)?$ ]];then
		exit 1
	fi
fi

#check branch
for i in ${ALL_PROJECT_FOLDER[@]}
do
	cd $REPO_ROOT/$i
	if [ "`git branch | grep "^* " | cut -c 3-`" != "$STABLE_VERSION" ];then
		echo_color RED "\"$i\", not on \"$STABLE_VERSION\" branch, please check"
		exit 1
	fi
done

####################################################################################

echo_color YELLOW "Begin finish stable, please wait .."

#clean folder
check_and_remove "$TARGET_FOLDER_PATH/patch"
mkdir -p "$TARGET_FOLDER_PATH/patch"

for i in ${ALL_PROJECT_FOLDER[@]}
do
	mkdir -p $TARGET_FOLDER_PATH/patch/$i/commit
done

#exact patches
for i in ${ALL_PROJECT_FOLDER[@]}
do
	cd $REPO_ROOT/$i
	#TODO: change to master in future
	git format-patch ut_repo/stable_2.7.0 -o $TARGET_FOLDER_PATH/patch/$i/commit > /dev/null 2>&1
done

del_empty_folder "$TARGET_FOLDER_PATH/patch"

#store .cur_project
cp $REPO_ROOT/.cur_project $STABLE_FOLDER_PATH

#clean all
mrepo forall -c git reset --hard
mrepo forall -c git clean -df

#repo init & sync
#TODO: change to master in future
echo_color YELLOW "repo init all_stable_2.7.0.xml and sync"
mrepo init all_stable_2.7.0.xml
mrepo sync -d
mrepo abandon $STABLE_VERSION

echo_color GREEN "Finish \"$STABLE_VERSION\" success"
