#!/bin/bash -
IFS="
	 "
PATH=/usr/local/bin:/bin:/usr/bin
export PATH

date_from=
date_to=
days=
djob_file_path="$HOME""/djob_file/"
djob_list="$djob_file_path""djob_list"
djob_list_tmp="$djob_job_file_path""djob_list_tmp"

error()
{
	echo "$@" 1>&2
	usage_and_exit 1
}

usage_and_exit()
{
	echo "Usage: djob [--verbose][--complete][--date<xxxx>][--help]
			--date 20170314-20170315 : jobs from 20170314 to 20170315
			--date 3d : jobs within three days
			--date 1w : jobs within one week
			--date all : all jobs
			--verbose : show the detailed task information
			--complete : show complete jobs
			--help : show useage
		 "
	eval "exit $1"
}

title_print()
{
	local title=`sed -n 1p "$djob_list"`
	title=${title//:/    }
    echo $title
}

#job_print()
#@in job_line
job_print()
{
	if [ "z`echo "$1" | cut -s -d : -f 4`" != "z" ]
    then
        echo -e "\033[32m${1//:/   }\033[0m"
    else
        echo "${1//:/   }"
    fi
}

#show_job_update
#@in inner_number
show_job_update()
{
	awk 'BEGIN{eprint=0}
		{
			if($0~/\[update\]/)
				eprint=1;
			else if($0~/\[end update\]/)
				eprint=0;
			if(eprint)
				print;
		}' "$djob_file_path""$1".job
}

print_job_message()
{
#   show job info
	job_print "`sed -n "/^"$1":/p" "$djob_list"`"
#   show job update
	show_job_update "$1"
#   show job summarize, if exist 
	echo show_job_summarize
}

date_print()
{
	echo -e "\033[31m${1:0:4}.${1:4:2}.${1:6:2}\033[0m"
}

sort_job_list()
{
	sed -n "1p" "$djob_list" > "$djob_list_tmp"
	sed -n '2,$p' "$djob_list" | sort -t: -k4 -k5 >> "$djob_list_tmp"
	mv "$djob_list_tmp" "$djob_list"
}

#根据传入的date，来显示当前date的jobs
show_daily_job()
{
	if [ "$1" == "`date +\%Y\%m\%d`" ]
	then
		if [[ "$show_complete_job" -eq 1 ]]
		then
			cat "$djob_list" | while read line
			do
				if [[ "`echo -n "$line" | cut -s -d : -f 4`" =~ "$1" ]] || [[ -z "`echo -n "$line" | cut -s -d : -f 4`" ]]
				then
					job_print "$line"
				fi
			done
		else
			cat "$djob_list" | while read line
			do
				if [[ -z "`echo -n "$line" | cut -s -d : -f 4`" ]]
				then
					job_print "$line"
				fi
			done
		fi
	else
		cat "$djob_list" | while read line
		do
			if [[ "`echo -n "$line" | cut -s -d : -f 4`" =~ "$1" ]]
			then
				job_print "$line"
			fi
		done

	fi
}

#add_job()
add_job()
{
    local title_priority
	echo "new job format: title@youxianji"
	read -p "enter: " title_priority
	local title=`echo "$title_priority" | cut -s -d @ -f 1`
	local priority=`echo "$title_priority" | cut -s -d @ -f 2`
	if [ z$priority == z"" ] 
	then
		title="$title_priority"
		priority=1
		echo "Apply default priority 1"
	fi
	local current_max_num="`sed -n '2,$p' "$djob_list" | cut -s -d : -f 1 | sort -nr | head -1`"
	local inner_number=$(($current_max_num+1))
	echo ""$inner_number":"$title":"`date +\%Y\%m\%d\%H\%M`"::"$priority"" >> "$djob_list"
}

#edit_job()
edit_job_info()
{
	local inner_number
	read -p "enter innernumber: " inner_number
	echo "job format: title@priority"
	local title_priority
	read -p "enter: " title_priority
	local title=`echo "$title_priority" | cut -s -d @ -f 1`
	local priority=`echo "$title_priority" | cut -s -d @ -f 2`
	if [ z$priority == z"" ] 
	then
		title="$title_priority"
		echo "Apply default priority 1"
	fi
    local job_info=`sed -n "/^"$inner_number":/p" "$djob_list"`
	local date_create=`echo -n "$job_info" | cut -s -d : -f 3`
	local date_complete=`echo -n "$job_info" | cut -s -d : -f 4`
	sed -i "/^"$inner_number":/d" "$djob_list"
	echo ""$inner_number":"$title":"$date_create":"$date_complete":"$priority"" >> "$djob_list"
}

#show_job()
show_job()
{
    local choosen_job
	echo "enter job inner number"
    read choosen_job
    print_job_message "$choosen_job"
}
#del_job()
del_job()
{
	local choosen_job
    echo "enter job inner number"
    read choosen_job
	sed -i "/^"$choosen_job":/d" "$djob_list"
}

complete_job()
{
	local choosen_job
    echo "enter job inner number"
    read choosen_job
	local date="`date +\%Y\%m\%d\%H\%M`"
	sed -i -r "s/(^$choosen_job:.*:.*:)(:[0-9]$)/\1$date\2/g" "$djob_list"
}

#add_update()
add_update()
{
	local choosen_job
	echo "enter job inner number"
	read choosen_job
	echo "please enter update message: "
	local IFS_BAK="$IFS"
	IFS="\n"
	local message
	read  message
	IFS="$IFS_BAK"
	if [ ! -e "$djob_file_path""$choosen_job".job ]
	then
		cp "$djob_file_path"example.job "$djob_file_path""$choosen_job".job
	    local job_info=`sed -n "/^"$choosen_job":/p" "$djob_list"`
		local title=`echo -n "$job_info" | cut -s -d : -f 2`
	    local date_create=`echo -n "$job_info" | cut -s -d : -f 3`
	    local date_complete=`echo -n "$job_info" | cut -s -d : -f 4`
		local priority=`echo -n "$job_info" | cut -s -d : -f 5`
		sed -r -i "s/(内部编号:)/\1"$choosen_job"/g;s/(标题:)/\1"$title"/g;
				 s/(创建日期:)/\1"$date_create"/g;s/(完成日期:)/\1"$date_complete"/g;
				 s/(优先级:)/\1"$priority"/g" "$djob_file_path""$choosen_job".job
	fi
	sed -i "/end update/i`date +\%Y\%m\%d\%H\%M`" "$djob_file_path""$choosen_job".job
	sed -i "/end update/i$message" "$djob_file_path""$choosen_job".job
}

add_summarize()
{
	echo add_summarize
}

cal_date_from()
{
	echo cal_date_from
}

if [ "$#" -ne 0 ]
then
	while [ "$#" -gt 0 ]
	do
		case $1 in
		--date )
			case $2 in
			*d)
				#TODO : should fix, month is 30days
				days=`echo "$2" | sed -r "s/^([0-9]+)d/\1/g"`
				date_from=$((`date +\%Y\%m\%d`-$days))
				date_to=`date +\%Y\%m\%d`
				shift
				;;
			*)
				break
				;;
			esac
			;;
		--help | -h | '--?' | '-?' )
			usage_and_exit 0
			;;
		-* | --* )
			error "Unrecongnized option: $1"
			;;
		*)
			break
			;;
		esac
		shift
	done
else
	date_from=`date +\%Y\%m\%d`
	date_to=$date_from
	show_complete_job=0
fi

sort_job_list
title_print
for((i="$date_from" ; i<="$date_to" ; i++))
do
	date_print "$i"
	show_daily_job "$i"
done

read nouse
echo "What to do next:
 1 : add new job
 2 : edit job info
 3 : add update
 4 : show job
 5 : del job
 6 : complete job
 7 : add summarize
 0 : exit"
read -p "your choose: " choose
case "$choose" in
1)
    add_job
	;;
2)
	edit_job_info
	;;
3)
	add_update
	;;
4)
	show_job
    ;;
5)
	del_job
	;;
6)
	complete_job
	;;
7)
	add_summarize
	;;
0)
    exit 0
    ;;
*)
	error "Unrecongnized option"
    ;;
esac
